var fs=require('fs')
fs.writeFileSync("hello.txt","How are you")
fs.appendFileSync("hello.txt","\n I am fy")
var data =fs.readFileSync("hello.txt")
console.log(data)
console.log(data.toString())
fs.copyFileSync("hello.txt","hii.txt")
fs.unlinkSync("hello.txt")
console.log("programe ended")